canvas:
  access_token: 4511~WCSGB3WbHDUmamuC5ktWnAWmRvIYbejFoCaG340oJ17IpePXQcka5GsTI6HJX7hW
  course_id: '145421'
flask:
  host_address: localhost
  port: 8081
led:
  host_address: 192.168.10.150
  port: 7346
mongodb: null
