canvas:
  access_token: 4511~WCSGB3WbHDUmamuC5ktWnAWmRvIYbejFoCaG340oJ17IpePXQcka5GsTI6HJX7hW
  course_name: Network Application Design
flask:
  host_address: localhost
  port: 5000
led:
  host_address: 192.168.10.150
  port: 7346
mongodb: null
